### ISSUE TITLE
CLI: Analyzers with DiagnosticSeverity.Info

### ISSUE THREAD

**Issue by Kasperki** [vad710/UnityEngineAnalyzer#16]
IAnalyzerExporter have hardcoded DiagnosticInfo.DiagnosticInfoSeverity MinimalSeverity.
Make that configurable.

**Comment by Kasperki** [comment]
I have made this update to my dev branch, but I do not want to make Pull request, until @vad710 can merge current pull requests, so I can rebase and this change easier to merge.

Cleaned diagnostics descriptions: https://github.com/Kasperki/UnityEngineAnalyzer/commit/885dd8b8ac7225f0ba36d598cee482f5c9a3edb4
Added command line parser: https://github.com/Kasperki/UnityEngineAnalyzer/commit/4b8f846aed6f04ad25c3eb60c7df9d288bac03b3
And finally Minimali Severity can be given as CLI argument: https://github.com/Kasperki/UnityEngineAnalyzer/commit/032779636ced7b5376bc0069ba5f1bf1a8d020c4

**Comment by vad710** [comment]
I will try to get all the PRs wrapped up this week

**Comment by vad710** [comment]
I think it might be better to add the severity level we want in the config file - what are your thoughts on this?

**Comment by vad710** [comment]
Should be good to submit the new commits
