### ISSUE TITLE
Error when running Unit tests

### ISSUE THREAD

**Issue by Kasperki** [vad710/UnityEngineAnalyzer#21]
Latest master branch gives me error when running unit tests:
System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by vad710** [comment]
@Kasperki could we get a stack trace? do you happen to know if the issue is running any unit test or a specific one?

**Comment by Kasperki** [comment]
@vad710 oh yeah sorry,
It happens with every unit test.

System.TypeInitializationException: 'The type initializer for 'UnityEngineAnalyzer.Test.MetadataReferenceHelper' threw an exception.'

FileUtilities.OpenFileStream()
MetadataReferenceHelper:CreateFromFile()

**Comment by vad710** [comment]
hmm - that's odd - are you loading this with vs2017? and/or dotnet 4.6.1?

**Comment by Kasperki** [comment]
visual studio 2017 and the UnityEngineAnalyzer.Test project target framework is .NET 4.6.1

**Comment by vad710** [comment]
I just re-cloned the branch to see if I could reproduce it - but I am not getting the same error. I think there might be a dependency missing, but I am not sure what it is yet. Do you happen to have dotnet core 2.0 installed? I am not sure what else it could be, but we may need to look at your Fuslog to determine what's missing.

There does seem to be some related issues:
https://github.com/dotnet/corefx/issues/16322
https://github.com/dotnet/corefx/issues/16206
https://github.com/aspnet/EntityFrameworkCore/issues/6831

**Comment by Kasperki** [comment]
Yes I have dotnet core 2.0 installed, I'll test this with another environment tomorrow.
Could it affect that the MetadataReferenceHelper lives in Microsoft.CodeAnalysis.Common namespace and it looks like using netstandard1.3:  \UnityEngineAnalyzer\packages\Microsoft.CodeAnalysis.Common.2.4.0\lib\netstandard1.3\Microsoft.CodeAnalysis.dll ?

**Comment by Kasperki** [comment]
Exactly the same problem with my another computer as well

**Comment by vad710** [comment]
Thanks for checking! I do not have another environment to debug against right now. Are you getting a similar problem when you run the CLI?
Thanks!

**Comment by Kasperki** [comment]
I get the same error when running CLI.

**Comment by Kasperki** [comment]
The CLI got error: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

But after upgrading to Creators Update Fall it now works and the unit tests pass.

That is shame because I'm stuck with Anniversary update with my other pc.

**Comment by vad710** [comment]
hmm - I wonder if we can roll something back so that it's compatible with the Anniversary update

**Comment by Zod-** [comment]
Is there any fix yet for this? I want to add an analyzer but rather not do it without tests.

**Comment by vad710** [comment]
I've not looked at this - the current workaround is to install the Fall Anniversary Updates

**Comment by Zod-** [comment]
I have all of the updates installed, it's not working for me.

**Comment by vad710** [comment]
Are you getting the same error as Kasperki mentioned above? Could you please provide a stack trace? Thanks!

**Comment by Kasperki** [comment]
@Zod- This error should only happen when your PC does not have Fall Creator Update you can check if you have it from here: https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-fall-creators-update

Another error that I have got when running unit tests is when you have installed unity as 64-bit, it will install it to Program Files folder. And automatically the test runner will search it from Program Files (x86) folder. Then you need to set the Unit tests to run as 64-bit process: From the Visual Studio menu, choose Test, then choose Settings, and then choose Processor Architecture. Choose x64 to run the tests as a 64-bit process. https://msdn.microsoft.com/en-us/library/ee782531.aspx

**Comment by Zod-** [comment]
Can't you just add the dlls to the project? Right now you always need to have unity installed and it might even cause issues with different versions of dlls (in addition to the issues with the architecture).

**Comment by vad710** [comment]
@Zod- im pretty sure it would be illegal for us to distribute any of Unity's DLLs - the best we can do is to improve how we find the DLLs

**Comment by Kasperki** [comment]
Unit tests works fine in .net core unit test project.
Finding the unityengine.dll from custom folder is different problem
