### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by wpinaud** [vad710/UnityEngineAnalyzer#8]
Hello,

I love Unity Engine Analyzer and I integrated it into our SonarQube analysis system.
Also, I saw JetBrains was integrating all your work into the Rider IDE: https://github.com/JetBrains/resharper-unity/issues/107 and that's a great news.

But there is still a lot of interesting tickets in the GitHub kanban under the Projects tab, so I was wondering if you were still active on this project or completely absorbed by your work at Vuforia.

If you don't have much time to keep this project alive, I might start opening pull requests whenever I have time, because it's an amazing project.

**Comment by vad710** [comment]
hi @wpinaud ,

The project is indeed still alive! But my pace has been slower than in the Fall. I'd happily take your pull requests if you have suggestions. 

There's also a lot of new developments in this area. Have you seen Ian's talk? https://www.youtube.com/watch?v=_wxitgdx-UI&index=9&list=PLX2vGYjWbI0Rzo8D-vUCFVb_hHGxXWd9j

Vinny
